### ISSUE TITLE
Error generating soap Stub 

### ISSUE THREAD

**Issue by Andromeda1966** [benerone/soapStub#2]
Hi,
thanks a lot for this soap generator.
I have used it to generate a stup using this wsdl link :
[sdi](http://www.fatturapa.gov.it/export/fatturazione/sdi/ws/trasmissione/v1.0/TrasmissioneFatture_v1.0.wsdl)

in this way :
**node index.js -i http://www.fatturapa.gov.it/export/fatturazione/sdi/ws/trasmissione/v1.0/TrasmissioneFatture_v1.0.wsdl  -o riceviNotifiche.js**

but I got the error below:

> /Users/mauro/Shared/Source/Javascript/Test/soapStub/**index.js:112**
>     **var keys = Object.keys(obj);**

May you help me to understand what can I do to get the right Js code ?

Thanks in advance

Mauro

**Comment by benerone** [comment]
Bug found and fix done! Enjoy!

**Comment by Andromeda1966** [comment]
Awesome. Thanks
