### ISSUE TITLE
Example described not working

### ISSUE THREAD

**Issue by capoteSPS** [benerone/soapStub#3]
I have tried the example described in a Centos 6 getting the following error:

[aldeasa@localhost soapStub]$ node index.js -i https://svn.apache.org/repos/asf/airavata/sandbox/xbaya-web/test/Calculator.wsdl -o result.js

/home/aldeasa/dev/soapStub/index.js:21
var templateString = `{{#*inline "partialDesc"}}
                                  ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

Any idea?

**Comment by benerone** [comment]
Hi,
It works for me. I'm using node 6.11.2

I think your version of node is too old and doesn't support String template. (node version >=4.0)
See [https://stackoverflow.com/questions/32844871/cant-use-template-strings-in-node-js](https://stackoverflow.com/questions/32844871/cant-use-template-strings-in-node-js)

you can test node version using command : node -v

You must install a more recent version of node . See [https://tecadmin.net/install-latest-nodejs-and-npm-on-centos/](https://tecadmin.net/install-latest-nodejs-and-npm-on-centos/)

Is that good for you?

**Comment by capoteSPS** [comment]
Thank you very much!

I was using a very old distribution for testing. I have tried to update nodejs without success due to my OS version. I will update it.

Thanks!

**Comment by benerone** [comment]
You're welcome
